export default {
  LATEST_ZVEK: 'Latest ZVEK Damage, B',
  DAMAGE: 'Damage',
  NICKNAME: 'Nickname',
  BILLION: 'B',
  TRILLION: 'T',
  BACK: 'Back',
  ERROR: 'Something went wrong:',
  TRY: 'Try again',
  TUE: 'Tue',
  WED: 'Wed',
  THU: 'Thu',
  FRI: 'Fri',
  SAT: 'Sat',
  SUN: 'Sun',
};
