export default {
  LATEST_ZVEK: 'Latest ZVEK Damage, B',
  DAMAGE: 'Damage',
  NICKNAME: 'Nickname',
  BILLION: 'B',
  BACK: 'Back',
  ERROR: 'Something went wrong:',
  TRY: 'Try again',
  TUE: 'Tue',
  WED: 'Wed',
  THU: 'Thu',
  FRI: 'Fri',
  SAT: 'Sat',
  SUN: 'Sun',
  LAST: 'Last ZVEK',
  STAT: 'Statistics',
  CONTACTS: 'Contacts',
  NO_DATA: 'No data',
  GROW: 'ZVEK change',
  GUILD_RATING: 'Guild rating',
  NEWBIES: 'Newbies',
};
