export default {
  LATEST_ZVEK: 'Урон последнего ЗВЭК, млрд',
  DAMAGE: 'Урон',
  NICKNAME: 'Никнейм',
  BILLION: 'млд',
  TRILLION: 'трл',
  BACK: 'Назад',
  ERROR: 'Что-то пошло не так:',
  TRY: 'Попробуйте снова',
  TUE: 'Вт',
  WED: 'Ср',
  THU: 'Чт',
  FRI: 'Пт',
  SAT: 'Сб',
  SUN: 'Вс',
};
