export default {
  GROW: 'ZVEK change',
  TOP_PLAYERS: 'Top players of last ZVEKs',
  JUNNI_COEF: 'Disbalance factor',
  FORMULA: 'Equation:',
  WHERE: 'where',
  COUNT: '— number of players.',
  DAMAGE: '— player`s damage',
  AVARAGE_DAMAGE: '— avarage damage',
  AVARAGE_COUNT: 'arithmetic average',
  SMALL: '0.2−0.3: Damage is distributed fairly evenly.',
  MEDIUM: '0.5: Moderate inequality. There are a few players with significantly larger contributions, but the others also make a noticeable impact.',
  HARD:
    '0.8−1.0: Severe inequality. Damage is mainly concentrated among one or a few "top" players, while the rest have almost no impact on the overall result.',
  DATE: 'Date',
  TOP: 'Top 1,2,3',
  PERCENT: '% of overall damage',
  JINNI: 'The Gini coefficient.',
  DAMAGE_GUILD: 'Guild damage, B',
  CHANGES: 'Changes',
  NO_DATA: 'No data',
  INCREASE: 'increased by',
  DECREASE: 'decreased by',
};
